pip install flask
pip install flask-wtf
pip install flask-sqlalchemy
pip install pandas
pip install numpy
pip install requests
pip install flask-mail
pip install flask-login
pip install pyjwt
pip install python-dotenv
pip install flask-migrate
pip install flask-bootstrap 
pip install flask-moment
pip install flask-uploads